# mtgjson config file

mtgjson:
  base_url: http://gatherer.wizards.com

cache:
  provider: redis
  #provider: fs
  #provider: none
  #provider: memory
  expires: 3600000000

  # Path is relative to the mtgjson root folder, or
  # from the root filesystem if it starts with a "/" forward slash.
  #path: .

  # For redis
  host: localhost
  port: 6379

